JobSeeker/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

import tugas2_Login.urls as tugas2_Login
import tugas2_Profile.urls as tugas2_Profile
import tugas2_forum.urls as tugas2_forum


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tugas2_Login/', include(tugas2_Login,namespace='tugas2_Login')),
    url(r'^tugas2_forum/', include(tugas2_forum,namespace='tugas2_forum')),
    url(r'^tugas2_Profile/', include(tugas2_Profile,namespace='tugas2_Profile')),

]

tugas2_Login/urls.py
from django.conf.urls import url
from .views import index,addPost,deletePost,addComment
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', addPost, name='add'),
    url(r'^delete/$',deletePost, name='delete'),
    url(r'^comment/$',addComment, name='comment'),
]

tugas2_Profile/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

tugas2_forum/urls.py
from django.conf.urls import url
from .views import index,addPost,deletePost,addComment

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add/$', addPost, name='add'),
    url(r'^delete/$',deletePost, name='delete'),
    url(r'^comment/$',addComment, name='comment'),
]

tugas2_Login/models.py
from django.db import models

# Create your models here.

tugas2_Profile/models.py
from django.db import models

# Create your models here.

    

tugas2_forum/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Forum(models.Model):
    user_id = models.CharField(max_length=200)
    # title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    body = models.CharField(max_length=200)
    # created_date = models.DateTimeField(default=timezone.now)

    
class Comment(models.Model):
    user_id = models.CharField(max_length=200)
    post = models.ForeignKey(Forum, related_name='comments')
    name = models.CharField(max_length=200)
    body = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    class Meta:
        ordering = ['created_date']

tugas2_forum/forms.py
from django import forms

class Postingan(forms.Form):
    attrs = {
        'type' : 'text',
        'class' : 'form-control',
        'placeholder' : 'Say something!',
        'rows':'3',
        'cols':'3',
    }
    content = forms.CharField(widget=forms.Textarea(attrs=attrs))
    

tugas2_Login/views.py
from django.shortcuts import render,redirect
from tugas2_forum.models import Forum, Comment
from tugas2_forum.forms import Postingan

# Create your views here.
response = dict()
def index(request):
    forum = Forum.objects.all()
    response['forum'] = forum
    comment = Comment.objects.all()
    response['comment'] = comment
    response['Postingan'] = Postingan
    html = 'tugas2_Login/tugas2_Login.html'
    response['author']= ' ilham pamungkas'
    return render(request, html, response)

def addPost(request):
    if request.method == 'POST':
        form = Postingan(request.POST or None)
        response['form'] = form
        if form.is_valid():
            response['content'] = request.POST['content']
            Forum.objects.create(body=form.cleaned_data['content'])
            return redirect ('/tugas2_Login/')
        else:
            return redirect ('/tugas2_Login/')

def deletePost(request):
    try:
        idStatus = request.POST['flag']
        Forum.objects.filter(id=idStatus).delete()
    except ValueError or KeyError:
        pass
    return redirect ('/tugas2_Login/')

def addComment(request):
    try:
        
        idStatus = request.POST['flag']
        target = Forum.objects.filter(id=idStatus)
    except ValueError or KeyError:
        pass
    form = Postingan(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['content'] = request.POST['content']
        Comment.objects.create(post_id=idStatus,body=form.cleaned_data['content'])
        return redirect ('/tugas2_Login/')
    else:
        return redirect ('/tugas2_Login/')

tugas2_Profile/views.py
from django.shortcuts import render

# Create your views here.
response = {}
def index(request):
    return render(request, 'tugas2_Profile/tugas2_Profile.html', response)

tugas2_forum/views.py
from django.shortcuts import render, redirect
from .models import Forum, Comment
from .forms import Postingan

# Views boi

response = {}
def index(request):
    forum = Forum.objects.all()
    response['forum'] = forum
    comment = Comment.objects.all()
    response['comment'] = comment
    response['Postingan'] = Postingan
    html = 'tugas2_forum.html'
    return render(request, html ,response)

def addPost(request):
    if request.method == 'POST':
        form = Postingan(request.POST or None)
        response['form'] = form
        if form.is_valid():
            response['content'] = request.POST['content']
            Forum.objects.create(body=form.cleaned_data['content'])
            return redirect ('/tugas2_forum/')
        else:
            return redirect ('/tugas2_forum/')

def deletePost(request):
    try:
        idStatus = request.POST['flag']
        Forum.objects.filter(id=idStatus).delete()
    except ValueError or KeyError:
        pass
    return redirect ('/tugas2_forum/')

def addComment(request):
    try:
        
        idStatus = request.POST['flag']
        target = Forum.objects.filter(id=idStatus)
    except ValueError or KeyError:
        pass
    form = Postingan(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['content'] = request.POST['content']
        Comment.objects.create(post_id=idStatus,body=form.cleaned_data['content'])
        return redirect ('/tugas2_forum/')
    else:
        return redirect ('/tugas2_forum/')

templates/base/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html  lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="LAB 8">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
     <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas2_Login.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'js/tugas2_Login.js' %}"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato:700" rel="stylesheet"> 
    
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
        api_key: 81hohc9080x1lg
        authorize: true
        onLoad: onLinkedInLoad
    </script>
   
   <title>
       {% block title %} Tugas 2{% endblock %}
   </title>
</head>
<body>
   <header>
       {% include "partials/header.html" %}
   </header>
   <content>
           {% block content %}
               <!-- content goes here -->
           {% endblock %}
   </content>
   
   
   {% block javascript %}
   {% endblock %}
</body>

<footer>
       <!-- TODO Block Footer dan include footer.html -->
       {% block footer %}
       {% include "partials/footer.html" %}
       {% endblock %}
   </footer>
</html>

templates/partials/footer.html
<style>
    .footer {
      position: fixed;
      right: 0;
      bottom: 0;
      left: 0;
      padding: 0.2rem;
      background-color: #4b4b4b;
      height: 75px;
      
      
    }

    #button1{
       position: absolute;
       left: 50px;
       top: 18px;
       background-color: #FBDA00 !important;
       -webkit-box-shadow: 0px 3px 0px rgba(0, 0, 0, 0.3);
    -moz-box-shadow:    0px 3px 0px rgba(0, 0, 0, 0.3);
    box-shadow:         0px 3px 0px rgba(0, 0, 0, 0.3);
    font-family: Lato;
    }

    #button2{
       position: absolute;
       left: 300px;
       top: 18px;
       background-color: #006A99 !important;
       color: white;
       -webkit-box-shadow: 0px 3px 0px rgba(0, 0, 0, 0.3);
    -moz-box-shadow:    0px 3px 0px rgba(0, 0, 0, 0.3);
    box-shadow:         0px 3px 0px rgba(0, 0, 0, 0.3);
    font-family: Lato;
    }

    @media only screen and (min-width:320px) and (max-width:480px) { 
        .footer {
            position: fixed;
            right: 0;
            bottom: 0;
            left: 0;
            padding: 0.2rem;
            background-color: #c4c4c4;
            height: 75px;
            
            
         }

        #button1{
            position: absolute;
            left: 10px;
            top: 18px;
            background-color: #FBDA00 !important;
            -webkit-box-shadow: 0px 3px 0px rgba(0, 0, 0, 0.3);
    -moz-box-shadow:    0px 3px 0px rgba(0, 0, 0, 0.3);
    box-shadow:         0px 3px 0px rgba(0, 0, 0, 0.3);
            font-family: Lato;
            
        }
       

        #button2{
            position: absolute;
            left: 163px;
            top: 18px;
            background-color:   #006A99 !important;     
            -webkit-box-shadow: 0px 3px 0px rgba(0, 0, 0, 0.3);
    -moz-box-shadow:    0px 3px 0px rgba(0, 0, 0, 0.3);
    box-shadow:         0px 3px 0px rgba(0, 0, 0, 0.3);
    font-family: Lato;
        }
    }

    .IN-widget{
        margin-top: 23px;
        margin-left: 20px;
}
    
    
    </style>
    
    
    
    
    
    <div class="footer">
       
        
        <script type="in/Login"></script>
       

    </div>

templates/partials/header.html
{% load staticfiles %}

<nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <img class="navbar-brand" src="{% static 'home/LOGO2.png' %}" href="#">
        
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          
        </ul>
        
        <ul id="header" class="nav navbar-nav navbar-right">
          
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

tugas2_Login/templates/tugas2_Login/tugas2_Login.html
{% extends "base/base.html" %}}
{% load staticfiles %}
{% load static %}
{% block content %}
<div id="top_div">
    <div class="container"> 
     
    </div>    

    
</div>

<div id="bottom_div">
        
    <div class="container"> 
        <div class="flex">
            {% if forum %}
                {% for data in forum %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<div class="image-and-username">
								<p>
								<img class="image-fluid"  src = "{% static 'HalProfile/img/pict.jpg' %}" style= "max-width:50px; max-height: 50px;">
								<b>
								{{author}}
								</b>
								</p>
							</div>
							<div id="namaPerusahaan" >
                                Dummy
                            </div>
                            <div class="to-do-list-description">
                                {{data.body}}
                            </div>
                            <div class="to-do-list-date-added">
								<font color='gray'>
                                {{data.created_date}}
								</font>
                            </div>
                            <form id="form-{{data.id}}" method="post" action="{% url 'tugas2_Login:delete' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="flag" value="{{data.id}}"/>
                                    <input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="btn btn-primary float-right">
                            </form>
                            {% if comment %}
                            <p>Comments</p>
                            {% for comm in comment %}
                            {% if data.body == comm.post.body %}
                            <div class="comment-field">
                                    <p text-indent="50px">{{comm.name}}</p>
                            </div>
                            <div class="comment-field">
                                    {{comm.body}}
                            </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <div class="card">
                                        <div class="card-block">   
                        
                                            <!-- Form for new status -->
                                            <form class="card-text" method="POST" action="{% url 'tugas2_Login:comment' %}">
                                                {% csrf_token %}
                                                {{ Postingan }}
                                        </div>
                                    </div>
                                    <button name="flag" value="{{data.id}}" type="submit" class="btn btn-primary float-right" style="margin-top: 2px" id="button">Comment</button>
                                </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data.
            </div>
            {% endif %}
        </div>
        
   
    

    </div> 
</div>
{% endblock %}

tugas2_Profile/templates/tugas2_Profile/tugas2_Profile.html
{% extends "base/base.html" %}}
{% load staticfiles %}
{% load static %}
{% block content %}
     
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">    
    <link rel="stylesheet" type="text/css" href="{% static 'css/tugas2_Profile.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <!-- bootstrap csss -->

</head>
<div class="container" id="bgContent">
      <div id = "over" class="text-center">
        <h3 style="text-align:center; color: black">
        <small><em> <p style="color: black"> <b> Welcome! </b> </p> </em></small>
        <hr style="border: 0.5px solid black" />​
        </h3>

        <img class="image-fluid"  src = "http://www.otextechnology.com/images/services/hucapital.png" style= "max-width:18%; max-height: 500px;  border-radius: 50%; margin-top: 20px">

        <h2 id = "namaPerusahaan" style="color:black text-align: center;"><b>Nama Perusahaan</b></h2>
        <h4 id = "deskripsi" style="color:black text-align: center;"> Deskripsi Perusahaan</h4>
        
        <button href = "#" class = "button"> lihat forum</button>
        <button class = "button"> Cari Mahasiswa</button>

    </div>

  <content >
  <hr style="border: 1px solid black" />​
      <div class="row">
          <table style="width:50%; margin-top: 5px; margin-left: 400px ;" align= "center";>
          <style>
            table, th, td {
              color: black;
              height: 35px;
              align-content: center;
            }
          </style>
              <tr >
              <th>Tipe Perusahaan</th>
              <td id = "tipe"><b></b></td>
              </tr>

              <tr>
              <th >Founded Year</th>
              <td id = "Year"><b></b></td>
              </tr>

              <tr>
              <th >Web Perusahaan</th>
              <td id = "website"><b></b></td>
              </tr>


              <tr>
              <th >Spesialisasi</th>
              <td id = "Spesialisasi"><b></b></td>
              </tr>

          </table>
          <p></p>
          <hr style="border: 1px solid black" />​
         
      </div>
       <hr style="border: 1px solid black">​
  </div>

  </content>
</div>


<script type="text/javascript">
  console.log("coba atas")
  getSessionDataCompany();

  function getSessionDataCompany(){
    console.log("ahha");
    var company = JSON.parse(sessionStorage.company);
    console.log (company);
    console.log("ahha");
    document.getElementById("namaPerusahaan").innerHTML = company.name;
    document.getElementById("deskripsi").innerHTML = '"'+company.description + '"';
    document.getElementById("tipe").innerHTML = company.companyType.name;
    document.getElementById("Year").innerHTML = company.foundedYear;
    document.getElementById("website").innerHTML = company.websiteUrl;
    document.getElementById("Spesialisasi").innerHTML = company.specialties.values[0] + ", " + company.specialties.values[1];

  }

</script>
</html>
{% endblock %}

tugas2_forum/templates/tugas2_forum.html
{% extends "base/base.html" %}}
{% load staticfiles %}
{% load static %}
{% block content %}

<div class="container" id="bgContent">
	<content >

		<div class="flex">
            {% if forum %}
                {% for data in forum %}
                    <div class="flex-item">
                        <div class="to-do-list">
							<div class="image-and-username">
								<p>
								<img class="image-fluid"  src = "{% static 'HalProfile/img/pict.jpg' %}" style= "max-width:50px; max-height: 50px;">
								<b>
								{{author}}
								</b>
								</p>
							</div>
							<div id="namaPerusahaan" >
                                Dummy
                            </div>
                            <div class="to-do-list-description">
                                {{data.body}}
                            </div>
                            <div class="to-do-list-date-added">
								<font color='gray'>
                                {{data.created_date}}
								</font>
                            </div>
                            <form id="form-{{data.id}}" method="post" action="{% url 'tugas2_forum:delete' %}">
                                    {% csrf_token %}
                                    <input type="hidden" name="flag" value="{{data.id}}"/>
                                    <input id = "submit{{data.id}}" id="delete-{{data.id}}" type="submit" data-id="{{data.id}}" value="Delete" class="btn btn-primary float-right">
                            </form>
                            {% if comment %}
                            <p>Comments</p>
                            {% for comm in comment %}
                            {% if data.body == comm.post.body %}
                            <div class="comment-field">
                                    <p text-indent="50px">{{comm.name}}</p>
                            </div>
                            <div class="comment-field">
                                    {{comm.body}}
                            </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <div class="card">
                                        <div class="card-block">   
                        
                                            <!-- Form for new status -->
                                            <form class="card-text" method="POST" action="{% url 'tugas2_forum:comment' %}">
                                                {% csrf_token %}
                                                {{ Postingan }}
                                        </div>
                                    </div>
                                    <button name="flag" value="{{data.id}}" type="submit" class="btn btn-primary float-right" style="margin-top: 2px" id="button">Comment</button>
                                </form>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center">
                <strong>Oops!</strong> Tidak ada data.
            </div>
            {% endif %}
        </div>
        <div class="card">
                <div class="card-block">

                    <!-- Form for new status -->
                    <form class="card-text" method="POST" action="{% url 'tugas2_forum:add' %}">
                        {% csrf_token %}
                        {{ Postingan }}
                </div>
            </div>
            <button type="submit" class="btn btn-primary float-right" style="margin-top: 2px" id="button">Submit</button>
        </form>
    
        
	</content>
</div>

<script type="text/javascript">
    $(document).ready(function(){
            {% for post in forum %}
         
                $(".comment-field-{{ post.id }}").hide();
                $("#toggle-comments-{{ post.id }}").click(function(){
                    $(".comment-field-{{ post.id }}").toggle();
                });
        
            {% endfor %}
        });
  console.log("coba atas")
  getSessionDataCompany();

  function getSessionDataCompany(){
    console.log("ahha");
    var company = JSON.parse(sessionStorage.company);
    console.log (company);
    console.log("ahha");
    // document.getElementById("namaPerusahaan").innerHTML = company.name;
    // document.getElementById("deskripsi").innerHTML = '"'+company.description + '"';
    // document.getElementById("tipe").innerHTML = company.companyType.name;
    // document.getElementById("Year").innerHTML = company.foundedYear;
    // document.getElementById("website").innerHTML = company.websiteUrl;
    // document.getElementById("Spesialisasi").innerHTML = company.specialties.values[0] + ", " + company.specialties.values[1];

    $("form").append('<input type="hidden" name="id_perusahaan" value="' + company.id + '"/>');

  }
</script>

{% endblock %}  